# Generated 2 manifests
---
apiVersion: v1
data:
  greeting: hello from alpha
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: git-alpha
  name: alpha
  namespace: alpha-namespace
---
apiVersion: v1
data:
  greeting: hello from beta
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: git-beta
  name: beta
  namespace: beta-namespace
