# Generated 2 manifests
---
apiVersion: v1
data:
  environment: production
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: clusters-production
  name: cluster-info
  namespace: production-namespace
---
apiVersion: v1
data:
  environment: staging
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: clusters-staging
  name: cluster-info
  namespace: staging-namespace
