package main

import (
	"context"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	renderer "github.com/lorenzbischof/local-argocd-renderer"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"sigs.k8s.io/yaml"
)

// version is set at build time via -ldflags "-X main.version=..."
var version = "dev"

func main() {
	var applicationFile = flag.String("app", "", "Path to an Application or ApplicationSet manifest (use '-' for stdin)")
	var applicationDir = flag.String("dir", "", "Directory to scan recursively, rendering every Application and ApplicationSet found in it")
	var clustersFile = flag.String("clusters", "", "Path to a file or directory with Argo CD cluster secrets, used by the ApplicationSet cluster generator")
	var includeApplications = flag.Bool("include-applications", false, "Also emit the Application resources themselves, including the ones generated by an ApplicationSet")
	var includeTests = flag.Bool("include-tests", false, "Keep the test hooks Helm charts ship, which are dropped by default")
	var outputDir = flag.String("output-dir", "", "Write manifests to <dir>/<application>/<kind>-<name>.yaml instead of stdout")
	var quiet = flag.Bool("quiet", false, "Suppress progress output on stderr")
	var showVersion = flag.Bool("version", false, "Print the version and exit")
	var doSelfUpdate = flag.Bool("self-update", false, "Replace this binary with the latest release")
	var checkUpdate = flag.Bool("check-update", false, "Report whether a newer release exists, without installing it")
	flag.Parse()

	if *showVersion {
		fmt.Println(version)
		return
	}

	// Handled before --app/--dir is required: updating is not a render.
	if *doSelfUpdate || *checkUpdate {
		if err := selfUpdate(context.Background(), version, *checkUpdate); err != nil {
			fmt.Fprintf(os.Stderr, "Error: %v\n", err)
			os.Exit(1)
		}
		return
	}

	if (*applicationFile == "") == (*applicationDir == "") {
		fmt.Fprintf(os.Stderr, "Error: exactly one of --app and --dir is required\n")
		fmt.Fprintf(os.Stderr, "Usage: %s --app <file> | --dir <dir>\n", os.Args[0])
		fmt.Fprintf(os.Stderr, "Examples:\n")
		fmt.Fprintf(os.Stderr, "  %s --app app.yaml\n", os.Args[0])
		fmt.Fprintf(os.Stderr, "  %s --app appset.yaml --clusters clusters.yaml\n", os.Args[0])
		fmt.Fprintf(os.Stderr, "  %s --dir apps/\n", os.Args[0])
		fmt.Fprintf(os.Stderr, "  %s --dir apps/ --include-applications --output-dir rendered\n", os.Args[0])
		fmt.Fprintf(os.Stderr, "  cat app.yaml | %s --app -\n", os.Args[0])
		os.Exit(1)
	}

	ctx := context.Background()
	opts := renderer.TemplateOptions{
		ApplicationFile:     *applicationFile,
		ApplicationDir:      *applicationDir,
		RepoRoot:            ".",
		ClustersFile:        *clustersFile,
		IncludeApplications: *includeApplications,
		IncludeHelmTests:    *includeTests,
	}

	result, err := renderer.Template(ctx, opts)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}

	// Report any warnings
	for _, warning := range result.Warnings {
		fmt.Fprintf(os.Stderr, "Warning: %s\n", warning)
	}

	if *outputDir != "" {
		if err := saveManifests(result, *outputDir, *quiet); err != nil {
			fmt.Fprintf(os.Stderr, "Error: %v\n", err)
			os.Exit(1)
		}
		return
	}

	printManifests(result)
}

func printManifests(result *renderer.TemplateResult) {
	fmt.Printf("# Generated %d manifests\n", len(result.Objects))
	fmt.Println("---")

	// Parse and output manifests
	for i, object := range result.Objects {
		if i > 0 {
			fmt.Println("---")
		}

		yamlBytes, err := yaml.Marshal(object)
		if err != nil {
			fmt.Println(err)
			os.Exit(1)
		}

		fmt.Printf("%s", yamlBytes)
	}
}

// saveManifests writes one file per object, grouped into a directory per rendered
// Application, so that an ApplicationSet ends up as one directory per generated
// Application.
func saveManifests(result *renderer.TemplateResult, outputDir string, quiet bool) error {
	for _, app := range result.Applications {
		if err := saveManifestsToFiles(app.Objects, outputDir, app.Name, quiet); err != nil {
			return err
		}
	}

	return nil
}

func saveManifestsToFiles(objects []*unstructured.Unstructured, outputDir, appName string, quiet bool) error {
	appDir := filepath.Join(outputDir, appName)
	if err := os.MkdirAll(appDir, 0755); err != nil {
		return fmt.Errorf("failed to create app directory: %w", err)
	}

	// Group objects by kind for better organization
	kindCounts := make(map[string]int)

	for _, object := range objects {
		kind := object.GetKind()
		if kind == "" {
			kind = "unknown"
		}

		kindCounts[kind]++

		var filename string
		if name := object.GetName(); name != "" {
			if kindCounts[kind] == 1 {
				filename = fmt.Sprintf("%s-%s.yaml", strings.ToLower(kind), name)
			} else {
				filename = fmt.Sprintf("%s-%s-%d.yaml", strings.ToLower(kind), name, kindCounts[kind])
			}
		} else {
			filename = fmt.Sprintf("%s-%d.yaml", strings.ToLower(kind), kindCounts[kind])
		}

		filePath := filepath.Join(appDir, filename)

		yamlBytes, err := yaml.Marshal(object)
		if err != nil {
			return fmt.Errorf("failed to marshal object: %w", err)
		}

		if err := os.WriteFile(filePath, yamlBytes, 0644); err != nil {
			return fmt.Errorf("failed to write file %s: %w", filePath, err)
		}

		if !quiet {
			fmt.Fprintf(os.Stderr, "Saved: %s\n", filePath)
		}
	}

	if !quiet {
		fmt.Fprintf(os.Stderr, "Generated %d manifests for application '%s' in directory: %s\n", len(objects), appName, appDir)
	}

	return nil
}
