# Generated 2 manifests
---
apiVersion: v1
data:
  greeting: hello from one
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: list-one
  name: one
  namespace: one-namespace
---
apiVersion: v1
data:
  greeting: hello from two
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: list-two
  name: two
  namespace: two-namespace
